[package]
name = "recipe-book"
version = "0.1.0"
authors = ["Austin Ray <austin@austinray.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
rusqlite = "0.24.2"
serde = "1.0"
serde_json = "1.0"
